name: PCC
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - tk
  - black
  - pillow
  - pip
  - pip:
    - opencv-python
    - -e src/PCC/

